### ISSUE TITLE
Redesigning UI elements

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Recruit-a-thon#10]
The existing elements have scaling issues on data load via db, try to fix the issue and raise a PR.

**Comment by harshit-saraswat** [comment]
There's a lot of UI issues like for starters on login page the eye icon doesn't align with password input field and the Invalid credentials error is hidden behind the fields. Do you mind if I work on it? Can you assign this to me? I'll be available to work on this during Hacktober fest in October.

**Comment by rexdivakar** [comment]
Assigning it to u.

**Comment by harshit-saraswat** [comment]
Hey @rexdivakar can you review this PR?
