### ISSUE TITLE
Email log

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Recruit-a-thon#12]
Create/Use the function to share the email log.txt file to the admin email id.

**Comment by harshit-saraswat** [comment]
So to be clear, you need a method/function which whenever called, sends the logfile.txt from Extras folder to the Admin Email right? Or do you also need a UI addition for that or something? I might be interested in working on it.

**Comment by rexdivakar** [comment]
This issue has been created for the email, but you are happy to work on Adding UI elements for refind process.

**Comment by TechTarun** [comment]
@rexdivakar I also want to work on this issue, I have previously developed similar feature in my internship. Please assign me to it.

**Comment by rexdivakar** [comment]
Hi @TechTarun  this issue is already assigned, may be u can help us with scheduling the mail-- create a trigger function that will automatically call the email method to send the mail log. Let me know if ur interested i can create a new issue and assign it on ur name 

Feel free to drop in https://discord.gg/59TDJgt

**Comment by harshit-saraswat** [comment]
Hey @rexdivakar in the mail.py file we have an email function, can you mention specific details about what all is to be done?

**Comment by rexdivakar** [comment]
Sorry for poor coding, it was a quick shot @harshit-saraswat 

So method **email_content(ip, mail)**  
when ip==1 and mail== (email_id) send a email to the preview email to candidates 
when ip==2 and mail== (email_id) send a email to the interview email to candidates 
and when ip==3 and mail== (email_id) This one sends the entire logs of the system to the system admin email_id

**Comment by harshit-saraswat** [comment]
Okay then as per the issue I've to work on the third condition? So do I need to write logic to append logs.txt file to mail body and send to admin or something else?

**Comment by rexdivakar** [comment]
Well when calling that function in flask app our app gets down due to the time lag that takes for the method to get executed, we need it to be fixed !

**Comment by harshit-saraswat** [comment]
Okay noted!
